words = [
    "domi",
    "ebnf",
    "evaluable",
    "globbing",
    "kumi",
    "lto",
    "myapp",
    "mylib",
    "myproject",
    "niekdomi",
    "opengl",
    "programmatically",
    "tty",
    "ℹ",
]
