words = [
    "armv",
    "asio",
    "ast's",
    "avx",
    "bazel",
    "ccache",
    "clangd",
    "cmake",
    "cppcheck",
    "cxx",
    "dfs",
    "ebnf",
    "editorconfig",
    "globbing",
    "hwm",
    "imgui",
    "kumi",
    "kumi's",
    "lto",
    "mavx",
    "mfma",
    "mockup",
    "myapp",
    "mylib",
    "myproject",
    "ndebug",
    "openssl",
    "pthread",
    "reimagines",
    "reimplementation",
    "rtti",
    "sched",
    "spdlog",
    "stmts",
    "superset",
    "topo",
    "vcpkg",
    "wextra",
    "wpedantic",
    "wshadow",
]

ignore_paths = [
    "tests/**/*",
]

include_paths = [
    "**/*.rs",
    "**/*.md",
]
