words = [
  "AST's",
  "Cppcheck",
  "HWM",
  "Kumi",
  "avx",
  "ccache",
  "cxx",
  "ebnf",
  "emscripten",
  "freebsd",
  "globbing",
  "imgui",
  "kumi's",
  "lto",
  "minsizerel",
  "myapp",
  "mylib",
  "netbsd",
  "openbsd",
  "prebuild",
  "pthread",
  "relwithdebinfo",
  "riscv",
  "spdlog",
  "ssse",
  "stmts",
  "wasi",
]

ignore_paths = [
  "tests/**/*",
]

include_paths = [
  "**/*.rs",
  "**/*.md",
]
